# Generated by Django 4.1.2 on 2022-11-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_staff_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='job',
            field=models.CharField(default='no asignado', max_length=300),
        ),
    ]
