# Generated by Django 4.1.2 on 2022-11-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_department_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='job',
        ),
        migrations.AddField(
            model_name='staff',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.jobs'),
        ),
    ]
