# Generated by Django 4.1.3 on 2022-11-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_questions_alter_staff_number_evaluations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='number',
            field=models.IntegerField(),
        ),
    ]
