# Generated by Django 4.1.2 on 2022-11-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_remove_department_evaluation_evaluation_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.questions')),
            ],
        ),
    ]
