# Generated by Django 4.1.3 on 2022-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
