# Generated by Django 4.1.3 on 2022-11-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0016_staff_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='questions',
        ),
    ]
